name: isha
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.1+44

environment:
  sdk: ^3.5.1

flavors:
  dev:
    applicationIdSuffix: .dev
    versionNameSuffix: -dev
  uat:
    applicationIdSuffix: .uat
    versionNameSuffix: -uat
  prod:
    applicationIdSuffix: ""
    versionNameSuffix: ""

defaultEnv: uat

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  yaml: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true